spring:
  application:
    name: algusto

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    h2:
      console:
        enabled: true  # Gives you a web UI at /h2-console
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
